version: '3.1'

services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 7070:7070
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: 'false'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://appuser:appuserpassword@103.191.51.220:27017/BestVcom
      DB_NAME: BestVcom
      DB_USER: appuser
      DB_PASS: appuserpassword
      AUTH_SECRET_KEY: SecretKey123456789
      BASE_API_URL: api.beselectronics.com.bd
    depends_on:
      - mongo
